name: pr-verification

on:
  pull_request:
    types:
      - opened


jobs: 
  runs-on: ubuntu-latest
  steps:
    - name: getting pr 
      run: |
         echo ${{ github.event.pull_request.head.sha }}
  